Update ubuntu.yml

diff --git a/.github/workflows/ubuntu.yml b/.github/workflows/ubuntu.yml
--- a/.github/workflows/ubuntu.yml
+++ b/.github/workflows/ubuntu.yml
@@ -194,6 +194,11 @@ jobs:
                 lsof file procps cron ntpdate \
                 wireless-regdb rsync wpasupplicant perl \
                 --no-install-recommends
+      
+              dpkg -l openssh-server network-manager | grep -c '^ii' | grep -q '^2$' || {
+                echo 'ERROR: 关键包安装不完整'
+                exit 1
+              }
 
               apt-get upgrade -y
               apt-get clean && rm -rf /var/lib/apt/lists/*
@@ -216,7 +221,7 @@ jobs:
                 --no-install-recommends
               apt-get install -y wpasupplicant
 
-              dpkg -l openssh-server network-manager rsync | grep -c '^ii' | grep -q '^3$' || {
+              dpkg -l openssh-server network-manager | grep -c '^ii' | grep -q '^2$' || {
                 echo 'ERROR: 关键包安装不完整'
                 exit 1
               }
